### ISSUE TITLE
Doesn't seem to work as expected

### ISSUE THREAD

**Issue by nboliver** [anselmh/object-fit#36] opened 2015-06-30 17:02 UTC
Image shows until the JS is loaded, at which point it disappears. Tested in IE11, IE10 and IE9.
No JS errors.

**Comment by thehappycoder** [comment] 2015-07-07 12:59
Same for me. When I run "objectFit.polyfill" (android phone native android browser (Mozilla/5.0 (Linux; U; Android 4.2.1; ru-ru; PAP7600DUO Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30)), the image just disappears from the DOM.

**Comment by anselmh** [comment] 2015-07-08 14:43
Duplicate of #38.

**Closed by anselmh** 2015-07-08 14:43 UTC
Labels: bug, duplicate
