### ISSUE TITLE
Issues with object-fit: cover and html5 videos on Project Spartan/Microsoft Edge browser

### ISSUE THREAD

**Issue by cosmix** [anselmh/object-fit#32] opened 2015-06-18 14:07 UTC
As the title states, this does not work with videos with Microsoft's new browser on Windows 10 Build 10130.

**Comment by anselmh** [comment] 2015-06-18 14:08
Thanks for reporting, this is a duplicate of #29.

**Closed by anselmh** 2015-06-18 14:08 UTC
