### ISSUE TITLE
Firefox 17.0.6 script not responding

### ISSUE THREAD

**Issue by dmail** [anselmh/object-fit#28] opened 2015-05-05 10:42 UTC
Firefox 17.0.6 displays a popup indicating the script `polyfill.object-fit.min.js:1` is not responding.

I'll try to get more information about this and keep you informed.

**Comment by anselmh** [comment] 2015-05-05 11:05
Oh wow, what’s the case for using such an old, outdated Firefox version? How many images have you applied the polyfill on?

**Comment by dmail** [comment] 2015-05-05 14:06
One of our customer uses this firefox version for testing purpose.
I've used this polyfill on one <video> with `object-fit: cover`, no more.

**Comment by anselmh** [comment] 2015-06-08 11:19
@dmail hey, I cannot reproduce this on a Mac and the current version from `master` (not the latest published version) of this polyfill. Can you test this with the master source again by any chance? I’ll probably release a bugfix version soon.

**Comment by anselmh** [comment] 2015-06-23 18:01
I’m closing this now as not reproducible.

**Closed by anselmh** 2015-06-23 18:01 UTC
