### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by yukulele** [anselmh/object-fit#13] opened 2014-09-25 15:52 UTC
obect-fit.js is very slow on firefox

I think the probleme is ```getMatchedCSSRules``` polyfill

----

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=4792556)](https://www.bountysource.com/issues/4792556-slow?utm_source=4792556&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by O-Zone** [comment] 2015-01-12 13:19
Did anyone figure out whether this actually IS the same as https://github.com/anselmh/object-fit/issues/8, and are anyone working on a fix right now? I have a Bootstrap 3 site running the polyfill, and unfortunately I can confirm that this IS a problem in IE and FF.

**Comment by anselmh** [comment] 2015-01-12 13:31
It is the same. I’m sorry, I couldn’t find enough time to make the alternative implementation of the CSS parser. If anyone is willed to help, reach out to me and I’ll let you know what’s the plan.

**Comment by toobulkeh** [comment] 2015-01-12 14:10
@anselmh describe the plan here, I might have time, just not sure if I have the knowledge.

**Comment by anselmh** [comment] 2015-01-12 14:17
So the plan is to replace the CSS matcher / parser completely. The currently used script causes the trouble seen in bad performance on Firefox and IE. Replacing it with a better, proper solution might work and solve these problems. 

I already created an issue describing what needs to be done here: https://github.com/anselmh/object-fit/issues/19

**Comment by thany** [comment] 2015-01-15 12:51
I've got a workaround. It may not work for everyone, but for me, on my computer, on FF 35, replacing this:
```
var replacedElementStyles = objectFit.getComputedStyle(replacedElement);
var replacedElementDefaultStyles = objectFit.getDefaultComputedStyle(replacedElement);
```
With this:
```
var replacedElementStyles = { top: 0, right: 0, bottom: 0, left: 0, width: 0, height: 0, overflow: 0 },
    replacedElementDefaultStyles = replacedElementStyles;
```
Makes it a billion times faster.

**Comment by anselmh** [comment] 2015-01-15 13:45
Yes it does work in some cases. The main issue about this is that it doesn’t inherit other styles that were used on these elements before the x-tag got applied.

But maybe I could offer this as an option, you’re right.

I digged a little deeper into the issue and one way is to work around using the native CSSOM. While this has the effect of a better performance it would increase the polyfill weight from 18kb minified, non-gzipped to 48-50kb. I think that’s not really worth the trade-off so I’ll do a bit more research on how to optimize the polyfill when used on more than just a couple of elements on a site.

**Comment by thany** [comment] 2015-01-15 13:48
Oh well, just [one more](http://caniuse.com/#search=object-fit) FF version to go and IE will be the only remaining non-supporting browser. Then you can fairly safely abuse IE-only functions ;)

**Comment by anselmh** [comment] 2015-01-15 13:57
Yep, I know and that’s so awesome. Still the IE issue around and unfortunately IE sucks at the very same functions as Firefox does. And they have no plan yet on implementing `object-fit` so it won’t happen in the near future.

**Comment by O-Zone** [comment] 2015-01-16 16:08
Everyone in here interested in a real and long lasting solution should also remember to log in here: https://status.modern.ie/objectfitandobjectposition and whine about IE not planning on implementing object-fit. I'm not sure it will help, since there are lots of other features they should implement, and the competition is strong - but it won't hurt to try! ;-)

**Comment by anselmh** [comment] 2015-02-23 15:52
Duplicate of #22 so closing this now. Discussion is going on in the other issue.

**Closed by anselmh** 2015-02-23 15:52 UTC
Labels: bug, help-needed
