### ISSUE TITLE
Tests not working in IE9

### ISSUE THREAD

**Issue by electerious** [anselmh/object-fit#44] opened 2015-08-29 13:34 UTC
*Maybe a duplicate of #23*

I just tried the included tests in IE9 and they don't seem to work. All files are being loaded and there are no errors in the console. However, the image is missing for an unknown reason.

IE version: 9.0.8112

![ie9 - win7](https://cloud.githubusercontent.com/assets/499088/9562138/3f89e8ec-4e63-11e5-8e0e-38b464660729.png)

Works fine in IE10. Let me know if you need more information.

**Comment by anselmh** [comment] 2015-08-29 19:45
It is indeed a duplicate of #23 so I’m closing this one if that’s okay? I did some research but found no quick solution. If you find a solution, please let me know or send a PR :)

**Closed by anselmh** 2015-08-29 19:45 UTC
